= Membres
:awestruct-layout: default
:imagesdir: images

:homepage: http://sara.etsmtl.ca

== Contest 2016

The SARA is hosting an abstract writing competition to promote the importance of writing good scientific abstracts and the process of reviewing scientific articles. The contest has two different categories with many prizes to win. You can enter the competition in both categories!

* *Deadline:* Entries must be submitted by March 18, 2016!
* *Notification of winners:* The winners will be announced during “Journée des Découvertes” on April 12, 2016.

=== Abstract writing

Submit an abstract that explains clearly and concisely your research.

* *Length:* Abstracts must be between one to two (2) pages in length!
* *Language:* Abstracts must be written either in French or in English!
* *Format*: Abstracts must contain the following elements: title, name of the authors, author affiliation, text of the abstract, figures and/or tables (if used) and a list of cited references. The layout is at the discretion of the authors. Abstracts and reviews should be submitted as pdf files!
* *Prizes:* There will be a $300 prize for the person writing the best abstract and a prize of $150 for the second place!
* *Judges:* A committee of professors and researchers will evaluate the abstracts (and reviewing reports) to determine the winners!

To submit an abstract visit the page http://sara.etsmtl.ca/en/submit_paper/. After having read the section on requirements you can submit an article following the instructions in the section “Submit a draft paper”. 

=== Abstract reviewing

Play the role of a reviewer and write a reviewing report on an abstract you will be assigned.

* *Language:* Reviewing reports must be written either in French or in English!
* *Prizes:* There will be a $300 prize for the person writing the best review and a prize of $150 for second place!
* *Judges:* A committee of professors and researchers will evaluate the reviewing reports to determine the winners!

To enter as a reviewer, visit the page http://sara.etsmtl.ca/en/join_team/ and follow the instructions.
