= Home
:awestruct-layout: default
:imagesdir: images
:doctype: article
:icons:
:iconsdir: ./images/icons

== Welcome to SARA

=== Our mission

The *Paper Writing Help Service (SARA)* is a pilot project intended to help graduate students master the art of writing scientific articles.  Writing articles is an important and recurrent task in the life of a researcher but is often difficult the first few times.

SARA offers various forms of help for students who wish to improve the quality of their writing and become more familiar with the scientific publishing process:

====
* Several *documentary resources* that provide useful advice and hints to write good papers.
** link:/en/writing_guide[Practical guide for writing scientific papers]
** link:/en/style_guide[Guide on how to improve your writing style]
** link:/en/reviewing_guide[Guide to reviewing scientific papers]
** link:/en/resources[References to various resources (Web sites, books, articles, etc.) on those topics]

* A *free reviewing service* that allows every ÉTS student who needs it to obtain preliminary feedback on a first draft of his/her manuscript.  The reviews are *anonymous* and are done by *volunteer students* from ÉTS who have at least one publishing experience.  We believe that this external feedback can complement that of one’s thesis advisor.
** link:/en/submit_paper[Submit a paper to the reviewing service]
** link:/en/ask_help[Ask help on a specific writing topic]

* Training and reviewing opportunities for ÉTS students who want them and already have some publishing experience. By joining SARA as volunteer reviewers, these students acquire reviewing experience relevant to their future research careers.
** link:/en/join_team[Join our team of reviewers]
====

=== What SARA is not

SARA is not an article writing service, but an article writing *help* service. Thus, students who want to receive help from our volunteers must have a complete first draft of their manuscript ready, including figures, analysis, conclusions and references. To prepare this first draft, students can use some inspiration from our writing and style guides, soon to be available in both French and English on this site.
