= Submit paper
:awestruct-layout: default
:imagesdir: images

== SARA's paper reviewing service

The SARA offers a free paper reviewing service. This service allows ÉTS students to submit a draft of their paper and receive useful comments by people experienced in writing scientific papers.

=== Benefits

Why use this service? Here are several good reasons :

====
*  Get prompt feedback that is relevant to the improvement of your manuscript, from the perspective of a potential reader;
*  Learn to receive and react productively to criticism, which is an invaluable career skill; 
*  Become familiar with _EasyChair_, a real on-line manuscript submission system that is typical of systems used for many conferences;
*  Increase your chances of getting your work published in a good journal or conference proceedings.
====

=== Requirements

To use this service, you must:

====
*  Be registered as *a graduate student at ÉTS*;
*  Have *completed a first draft of your manuscript* in PDF format, in the format required by the conference or journal that you are targeting.  The draft does not need to be perfect, but it must be complete.  That is, it must minimally include a title, an abstract, an introduction, conclusions, a bibliography, the methodology and results, and must not have any empty sections or sections “to be completed”;
*  Have the *permission of your thesis advisor* and all of your co-authors before submitting to SARA;
*  Make sure that you *are not violating any confidentiality agreement* related to your research project, particularly if your project is part of an industrial collaboration;
*  Make sure that *your submission does not divulge information* that could compromise patent protection in the case where you or any of your co-authors is planning to commercialize the results of the research described in the manuscript.
====

=== Submit a draft paper

To submit a draft of your manuscript via our _EasyChair_ platform, you must have an _EasyChair_ account (click https://www.easychair.org/account/signup.cgi[here] if you do not have any), you must *agree to the following terms* and then click on the _Submit_ button.

++++

<form id="formsubmit" action="https://www.easychair.org/conferences/?conf=saraets2014" method="link">

<div id="terms" style="width:750px; height:225px; overflow:auto; border:solid 1px #ccc; padding-left:1em; padding-right:1em;">

<h5>Submission conditions</h5>

<p>In order to honor any confidentiality agreements your research may be subject to, you must not submit a draft of your manuscript to ÉTS’s article writing help service if :</p> 

<ol>
<li> The contents of your manuscript are linked with an industrial (or other) collaboration in which you participate, and you are not perfectly aware of the confidentiality agreements affecting this project.</li>

<li>Your research is part of an industrial (or other) collaboration that is subject to one or more confidentiality agreements and you have not verified the conformity of your draft with the professor in charge of the scientific content of the agreement or with the industrial partners involved in the project.</li>
</ol>

<p>In addition, you must not submit a draft of your manuscript to ÉTS’s article writing help service if :</p>

<ol start="3">
<li>You wish, with your co-inventors, to protect the technology described in the manuscript through a patent or another legal mechanism with help from the SPSIR (Service du Partenariat et du Soutien à l’Innovation et à la Recherche). If this is not done, your submission would then be considered a public divulgation, compromising the protection of the technology.</li>
</ol>

<p>Furthermore, if you submit a manuscript draft to ÉTS’s article writing help service with co-authors, all co-authors must be well represented.  The draft must not be submitted if one or more of the co-authors are in one of the three situations enumerated above.</p>

<input type="checkbox" name="submissionCheck" value="termsSubmissionAccept" required="required"> &nbsp; <b>I certify that I have read and understood the conditions enumerated on this page and that the contents of my submission are not affected by these conditions.</b>
</div>

<br>
<input type="submit" value="Submit">
</form>

<script src="http://jquery.bassistance.de/validate/jquery.validate.js"></script>
<script src="http://jquery.bassistance.de/validate/additional-methods.js"></script>

<script>
var is_explorer = navigator.userAgent.indexOf('MSIE') > -1;
var is_safari = navigator.userAgent.indexOf("Safari") > -1;

var div = document.createElement("div");
div.innerHTML = "<!--[if lt IE 10]><i></i><![endif]-->";
var ieLessThan10 = (div.getElementsByTagName("i").length == 1);


// Validate if not Safari or IE10+
if (is_safari || (is_explorer && ieLessThan10)) {
  jQuery.validator.setDefaults({
    debug: false,
    success: "valid"
  });

  $( "#formsubmit" ).validate({
    rules: {
      checkaccept: {
        required: true
      }
    }
  });
}
</script>
++++