= Workshops
:awestruct-layout: default
:imagesdir: images

:homepage: http://sara.etsmtl.ca

== Workshops

SARA and the ÉTS library offer workshops on a variety of subjects related to scientific writing. For more information and for the schedules of the workshops, go to the  
link:http://www.etsmtl.ca/Bibliotheque/Aide-et-formation/A-votre-service/Formations[workshop section of the ÉTS library’s website].

=== Writing better abstract to stand out (in french only)

Researchers will often decide if an article is worth reading by looking at this section of a few hundred words. Writing a good abstract is therefore essential to showcase your work. This workshop (presented in french only) presents the basic elements of good abstracts and provides hints on how to write them. More precisely, you will see :

* What is the objective of a scientific abstract;
* How to focus the abstract on the target audience;
* How to decide what to include;
* The structure of an abstract: objectives, methodology, results and conclusions;
* How to be concise;

Additional information:

* *Date :* Wednesday, February 10th 2016, 12 PM
* *Length :* 1 hour
* *Location :* Library lab (A-0241)