= Writing blitz
:awestruct-layout: default
:imagesdir: images

:homepage: http://sara.etsmtl.ca

== Writing Blitz

SARA and the ÉTS library present a “Writing Blitz” activity to help guide you in developing a regular routine for scientific writing. To register    
link:http://goo.gl/forms/iMUOZtnUmErHLzzM2[writing blitz subscription form].

=== Developing the “writer’s toolbox”

A regular writing routine helps you become a more fluid writer. This Writing Blitz activity offers the opportunity to write in a structured and motivating environment while benifiting from the support of SARA's team.

The activity will begin with a short presentation on different themes related to scientific writing. We will then dive into guided writing “sprint” exercises aimed at helping you start and targeting the main ideas of your article. The emphasis on these exercises will be to develop the habit of writing down research ideas in an easy to understand format, which can then form the basis for longer form scientific writing. All the activities will be interactive, with the chance for many questions and answers as well as feedback on your writing.

Additional information:

* *Date :* Thursday, September 22, 2016, 9 AM
* *Length :* 3 hours
* *Location :* Espace 3C in the library
