= Writing blitz
:awestruct-layout: default
:imagesdir: images

:homepage: http://sara.etsmtl.ca

== Writing Blitz

SARA regularly organizes a “Writing Blitz” activity to encourage you to write and to help you develop a regular writing routine. This activity affords you the opportunity to write in a motivating and structured environment under the support of SARA’s advisors.

=== Breakdown of the activity

A session begins with a short presentation with tips on how to write better. We then dive into guided writing “sprint” exercises aimed at helping you both unlock your “writing muscle“ and organise the main ideas of your article. The biggest part of the blitz will focus on letting students work on their own writing with help from SARA's team as needed. If you are presently working on a scientific text, we strongly encourage you to bring it along. If you are not presently working on a piece of scientific writing in particular, we will help you set a practical scientific writing goal that will get your thoughts flowing and put your writing muscles in action!

Information on the next session :

* *Subject :* The next session will focus on summarizing a scientific text for an informed reader. The objective is to help student who will participate in the "link:http://sara.etsmtl.ca/en/contest/[Ingenious Writers]" contest
* *Date :* Thursday February 23, 2017 at 1:30 PM
* *Length :* It’s up to the student to decide how long they want to participate. SARA’s team will be there until 5 PM
* *Location :* Espace 3C in the library
* *Registration :* To register, fill in the link:http://goo.gl/forms/iMUOZtnUmErHLzzM2[registration form]

