= Writing blitz
:awestruct-layout: default
:imagesdir: images

:homepage: http://sara.etsmtl.ca

== Writing Blitz

SARA regularly organizes a “Writing Blitz” activity to encourage you to write and to help you develop a regular writing routine. This activity affords you the opportunity to write in a motivating and structured environment under the support of SARA’s advisors.

=== Breakdown of the activity

A session begins with a short presentation with tips on how to write better. We then dive into guided writing “sprint” exercises aimed at helping you both unlock your “writing muscle“and organise the main ideas of your article.

Information on the next session :

* *Date :* Thursday November 24, 2016 at 9 AM
* *Length :* 1 hour
* *Location :* Espace 3C in the library
* *Registration :* To register, fill in the link:http://goo.gl/forms/iMUOZtnUmErHLzzM2[registration form]

Students who wish to stick around at the end of the activity will have the opportunity to get help from SARA’s advisors until 12am.

=== To bring

If you have some scientific writing that you are working on presently (or even completed), we encourage you to bring it to the Blitz. You can use it as a practical launching point to try the topics covered as well as a means of receiving feedback on your writing.
