= Accueil
:awestruct-layout: default
:imagesdir: images
:doctype: article
:icons:
:iconsdir: ./images/icons
:homepage: http://sara.etsmtl.ca

== Bienvenue au SARA

=== Notre mission

Le *Service d’Aide à la Rédaction d’Articles (SARA)* est un projet pilote mis sur pied dans le but d’aider les étudiants aux cycles supérieurs à devenir maîtres dans l’art de la rédaction d’articles scientifiques. Rédiger un article est une tâche importante et récurrente dans la vie d’un chercheur mais qui est souvent difficile lorsqu’on l’aborde les premières fois.  

Le SARA propose diverses formes d’aide aux étudiants qui désirent améliorer la qualité de leur rédaction et leur aisance à naviguer à travers le processus de publication scientifique:

====
* Plusieurs *ressources documentaires* donnant des conseils et astuces pour bien s’acquitter des tâches de rédaction et d'évaluation d'articles scientifiques.
** link:/fr/guide_redaction_accueil[Guide pratique pour l'écriture d'articles scientifiques]
** link:/fr/guide_style[Guide pour améliorer son style d'écriture]
** link:/fr/guide_evaluation[Guide sur comment évaluer des articles scientifiques]
** link:/fr/ressources[Références à diverses ressources (sites Web, livres, articles, etc.) sur ces thèmes]

* Un *service d’évaluation d’articles gratuit* qui permet à tout étudiant de l’ÉTS qui le souhaite d’obtenir des évaluations préliminaires d’une première ébauche de son article.  Les évaluations sont *anonymes* et sont réalisées par des *étudiants bénévoles de l’ÉTS* ayant déjà une expérience de publication. Nous pensons que ce regard extérieur complétera l’apport éventuel du directeur de recherche. 
** link:/fr/soumettre_article[Soumettre un article au service d'évaluation]
** link:/fr/nous_rejoindre[Demander de l'aide sur un aspect particulier de sa rédaction]

* Une *formation et des occasions d’arbitrage* aux étudiants de l’ÉTS qui le désirent et qui ont déjà une expérience de publication. Par la possibilité de se joindre à l’équipe du SARA en tant qu’évaluateur bénévole, ils acquièrent des expériences d’arbitrage fort pertinentes pour une future carrière en recherche.
** link:/fr/joindre_equipe[Se joindre à l'équipe d'évaluateurs]
====

=== Ce que le SARA n’est pas

Le SARA n’est pas un service de rédaction d’articles, mais un service d’*aide* à la rédaction d’articles. L’étudiant qui souhaite bénéficier de l’aide de nos bénévoles doit donc avoir déjà préparé une première ébauche complète de son article, incluant figures, analyse, conclusions et références.  Pour la réaliser, il pourra s’inspirer des guides de rédaction et de style disponibles sur ce site.

