title: SARA
gem_version: 0.5.2

asciidoctor:
  :eruby: erubis
  :attributes:
    idprefix: ''
    idseparator: '-'
    imagesdir: ../images

profiles:
  development:
  staging:
    base_url: http://staging.awestruct.org/
    deploy:
      host: awestruct.org
      path: /var/www/domains/awestruct.org/staging/htdocs/ 
  github:
    base_url: http://awestruct.github.com/awestruct.org/
    deploy:
      host: github_pages
  production:
    base_url: http://http://sara.logti.etsmtl.ca/
    minify: true
    deploy:
      host: sara-wadmin@sara.logti.etsmtl.ca
      path: /home/sara.logti.etsmtl.ca/public_hml/

intense_debate_acct: fa224495874e8d96bbf6f2dbcc26dac5
flattr_username: bobmcwhirter
