= Ateliers
:awestruct-layout: default
:imagesdir: images

:homepage: http://sara.etsmtl.ca

== Ateliers du SARA

Le SARA et le service de la bibliothèque présentent des ateliers sur différents sujets liés à la rédaction scientifique. Pour plus d’information et pour les horaires des 
ateliers, consulter la link:http://www.etsmtl.ca/Bibliotheque/Aide-et-formation/A-votre-service/Formations[section formation du site web de la bibliothèque de l’ÉTS].

=== Rédiger de meilleurs résumés pour mieux se démarquer

Le résumé est la vitrine de votre article scientifique pour les lecteurs potentiels. Souvent, c’est en lisant ce texte d’une centaine de mots que le chercheur va décider si votre texte vaut la peine d’être lu en entier. Cet atelier présente les bases d’un bon résumé ainsi que des trucs et astuces pour bien le rédiger. Plus précisément, vous verrez : 

* Quel est le but d’un résumé scientifique;
* Comment centrer son résumé sur le public cible;
* Comment déterminer le niveau de détail à inclure dans le résumé;
* La structure d'un résumé : objectifs, méthodologies, résultats, et conclusions;
* Comment être concis.

Informations supplémentaires:

* *Date :* Mercredi le 10 février 2016, 12 h
* *Durée :* 1 heure
* *Lieu :* Laboratoire de la bibliothèque (A-0241)