= Blitz de rédaction
:awestruct-layout: default
:imagesdir: images

== Blitz de rédaction

Le SARA et le service de la bibliothèque présentent une activité « Blitz de rédaction » qui vous aidera à trouver la motivation et à développer une routine de rédaction. Pour participer à l'activité, remplissez le   
link:http://goo.gl/forms/KR01A8UFcWWhcG5h1[formulaire d'inscription].

=== Développer la “boîte à outil du rédacteur”

Adopter une routine d'écriture facilite la rédaction. L'activité blitz de rédaction offre aux étudiants l'opportunité de venir rédiger dans un environnement motivant et structuré tout en bénéficiant du soutien des membres du SARA. 

La séance débute par une courte présentation sur l'intérêt de développer une routine de rédaction. Par la suite, une série d'exercices rapides de rédaction vous aideront à briser la glace et à cibler les idées principales de votre article. Ces exercices seront interactifs et offriront l'opportunité d'avoir une rétroaction sur votre texte et de poser des questions.

informations supplémentaires:

* *Date :* Mercredi le 6 juillet 2016 à 9h
* *Durée :* 3 heures
* *Lieu :* Espace 3C dans la bibliothèque
