= Blitz de rédaction
:awestruct-layout: default
:imagesdir: images

== Blitz de rédaction

Le SARA organise régulièrement des activités de « Blitz de rédaction » qui vous aideront à trouver la motivation nécessaire pour rédiger et à développer une routine. L’activité offre aux étudiants l’opportunité de rédiger dans un environnement motivant et structuré tout en bénéficiant du soutien des membres du SARA. 

=== Déroulement de l’activité

Une séance débute par une courte présentation visant à fournir des trucs pour mieux rédiger. Par la suite, une série d’exercices rapides vous aideront à briser la glace et à cibler les idées principales de votre article. 

Informations sur la prochaine séance :

* *Date :* Jeudi le 8 décembre 2016 à 13h30
* *Durée :* 1 heure
* *Lieu :* Espace 3C dans la bibliothèque
* *Inscription :* Pour participer à l’activité, remplissez le link:http://goo.gl/forms/KR01A8UFcWWhcG5h1[formulaire d'inscription]

Les étudiants qui le désirent auront la possibilité de rester sur place à la fin de l’activité afin de bénéficier de l’aide de l’équipe du SARA qui sera présente jusqu’à 17h.

=== À apporter

Si vous avez un texte scientifique sur lequel vous travaillez actuellement (ou même avez terminé), nous vous encourageons à l’apporter au Blitz. Vous pouvez l'utiliser comme point de départ pratique pour essayer les sujets couverts ainsi qu'un moyen de recevoir des commentaires sur votre rédaction.


