= Blitz de rédaction
:awestruct-layout: default
:imagesdir: images

== Blitz de rédaction

Le SARA organise régulièrement des activités de « Blitz de rédaction » qui vous aideront à trouver la motivation nécessaire pour rédiger et à développer une routine. L’activité offre aux étudiants l’opportunité de rédiger dans un environnement motivant et structuré tout en bénéficiant du soutien des membres du SARA. 

=== Déroulement de l’activité

Une séance débute par une courte présentation visant à fournir des trucs pour mieux rédiger. Par la suite, une série d’exercices rapides vous aideront à briser la glace et à cibler les idées principales de votre article. La majeure partie de l’atelier laisse les étudiants libre de travailler sur leur propre texte tout en demandant l'aide des membres du SARA au besoin. Si vous travaillez présentement sur un texte scientifique, nous vous encourageons à l’apporter au Blitz. Si vous travaillez présentement sur un texte scientifique, nous vous encourageons à l’apporter. Si vous n’avez pas de texte précis sur lequel travailler, nous vous aiderons à identifier un objectif de rédaction utile qui vous permettra de mettre en pratique vos habiletés de rédaction.

Informations sur la prochaine séance :

* *Date :* Jeudi le 26 janvier 2016 à 13h30
* *Durée :* Libre à l’étudiant de décider à quel moment il veut quitter. L’équipe du SARA est sur place jusqu’à 17h
* *Lieu :* Espace 3C dans la bibliothèque
* *Inscription :* Pour participer à l’activité, remplissez le link:http://goo.gl/forms/KR01A8UFcWWhcG5h1[formulaire d'inscription]



