= Joindre équipe
:awestruct-layout: default
:imagesdir: images

:homepage: http://sara.etsmtl.ca
// :homepage: http://localhost:4242

== Se joindre à l'équipe d'arbitres du SARA

Nous sommes à la recherche de personnes pour nous aider dans l'évaluation d'articles soumis au SARA par des étudiants.

=== Bénéfices 

Pourquoi se joindre à l’équipe d’arbitres de SARA? Voici plusieurs excellentes raisons: 

====
* Se familiariser avec le processus de soumission et d’évaluation d’articles;
* Élever son expertise professionnelle en rédaction technique;
* Améliorer vos habiletés de réflexion critique;
* Obtenir une vue d’ensemble de la recherche à l’ÉTS;
// * Développer le goût d’écrire vos propres articles;
* Ériger les bases d’une carrière de chercheur international.
====

=== Exigences

Pour devenir arbitre au SARA, vous devez satisfaire les conditions suivantes:

====
* Être *étudiant inscrit à l’ÉTS* aux cycles supérieurs ou personnel de recherche de l’ÉTS;
* Avoir déjà *au moins un article* publié ou accepté dans un journal ou une conférence;
* Posséder une *bonne maîtrise de l’anglais technique* (eh oui, nous ne publions que rarement en français).
====

Par ailleurs, vous devez également vous engager à:

====
* Lire et comprendre le link:/fr/guide_evaluation[Guide de l'évaluateur];
* Respecter nos règles de confidentialité (voir ci-dessous);
* Respecter les délais d’arbitrage.
====

=== Poser sa candidature

Pour poser sa candidature, veuillez remplir et soumettre le formulaire suivant:

++++

<form id="formjoindre" action="http://getsimpleform.com/messages?form_api_token=aa4b6f4f03643e5632535dacdd2d037e" method="post" enctype="multipart/form-data">
  
<input type='hidden' name='redirect_to' value='{homepage}/fr/confirmation_joindre' />

<h5>Contact:</h5>

<label for="prenom">
<span>Prénom:</span> 
<input type="text" name="prenom" required="required"><br>
</label>

<label for="nom">
<span>Nom:</span> 
<input type="text" name="nom" required="required"><br>
</label>

<label for="courriel">
<span>Courriel:</span> 
<input type="email" name="courriel" required="required"><br>
</label>

<h5>Programme d'études:</h5>

<input type="radio" name="cycle" value="phd" checked="checked"> &nbsp; Doctorat<br>
<input type="radio" name="cycle" value="maitrise"> &nbsp; Maîtrise<br>
<input type="radio" name="cycle" value="presonnelrech"> &nbsp; Personnel de recherche<br>

<br>
<select name="programme">
<option value="aerospatiale">Aérospatiale</option>
<option value="construction">Construction</option>
<option value="electrique">Électrique</option>
<option value="environnement">Environnement</option>
<option value="logiciel">Logiciel</option>
<option value="mecanique">Mécanique</option>
<option value="gpa">Production automatisée</option>
<option value="gti">Technologies des informations</option>
<option value="autre">--- Autre ---</option>
</select>

<h5>Expérience:</h5>

<p>Inclure un curriculum vitae décrivant vos expériences de travail et publications (PDF seulement):</p>
<input type='file' name="cv" accept="pdf" size = '50'><br>

<br>
<h5>Engagement à la confidentialité:</h5>

<div id="terms" style="width:750px; height:200px; overflow:auto; border:solid 1px #ccc; padding:1em;">

<p>Je me suis porté(e) volontaire pour participer à la mission du service d’aide à la rédaction d’articles de l’ÉTS.  Dans ce cadre, j’aurai à évaluer les articles de d’autres étudiants.  Je suis conscient que l’accès à ces articles non encore publiés constitue un privilège et je m’engage à préserver la confidentialité du contenu de ces articles :</p>

<ol>
<li>En ne diffusant aucune information sur leur contenu, sous aucune forme (orale, écrite, virtuelle);</li>
<li>En n’utilisant pas pour mon propre avantage (i.e. pour l’avancement de ma thèse ou de tout autre projet de recherche, de développement ou à caractère commercial) les informations contenues dans l’article qui n’ont pas déjà été publiées, et ce jusqu’au moment de leur publication officielle;</li>
<li>En détruisant les documents à la fin de chaque mandat d’évaluation.</li>
</ol>

<input id="checkaccept" type="checkbox" name="evaluationCheck" value="termesEvaluationAccept" required="required"> &nbsp; <b>J’ai lu et compris ce formulaire et je suis en accord avec son contenu.</b>
</div>

<br><br>
<input type="submit" value="Soumettre">

</form>

<script src="http://jquery.bassistance.de/validate/jquery.validate.js"></script>
<script src="http://jquery.bassistance.de/validate/additional-methods.js"></script>

<script>
var is_explorer = navigator.userAgent.indexOf('MSIE') > -1;
var is_safari = navigator.userAgent.indexOf("Safari") > -1;

var div = document.createElement("div");
div.innerHTML = "<!--[if lt IE 10]><i></i><![endif]-->";
var ieLessThan10 = (div.getElementsByTagName("i").length == 1);


// Validate if not Safari or IE10+
if (is_safari || (is_explorer && ieLessThan10)) {
  jQuery.validator.setDefaults({
    debug: false,
    success: "valid"
  });

  $( "#formjoindre" ).validate({
    rules: {
      checkaccept: {
        required: true
      }
    }
  });
}
</script>
++++